#!/bin/bash

#
#  illustration of using the ci tools to build & run this using command line and simavr
#
#  To compile against a specific version of arduino ide use --version=1.8.5 for example
# 

# directory containing this ci source file
pushd $(dirname "${BASH_SOURCE[0]}") >/dev/null
CI_DIR="$PWD"
popd >/dev/null

# au helper
. "$CI_DIR/../../ci/au"

# load missing libraries

au arduino "$@" --pref update.check=false --save-prefs

for library in ArduinoUnit
do
    if [ ! -d $(au sketchbook "$@")/libraries/$library ]
    then
	au arduino "$@" --pref update.check=false --install-library $library
    fi
done

if ! au compile_uno "$@"
then
    echo "compile_uno failed."
    exit 1
fi

# run the simulation, and print and record the output
au simavr_uno "$@" | tee "$CI_DIR/result.txt"

if diff --strip-trailing-cr "$CI_DIR/expect.txt" "$CI_DIR/result.txt"
then
    echo ok: result.txt and expect.txt match.
else
    echo "<expect and >result mismatches above."
    echo "fail: result.txt and expect.txt differ."
    exit 1
fi
